# Generated by Django 3.1.1 on 2021-12-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image1', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=24)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('product_price', models.FloatField()),
                ('image1', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=11)),
                ('address', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alabian_app.category')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alabian_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alabian_app.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alabian_app.product'),
        ),
    ]
