# Generated by Django 3.1.1 on 2021-12-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alabian_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamMember_name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('profile', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('Bio', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Team-Member',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'P-category'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product-Category'},
        ),
    ]
